"""Remove unused columns

Revision ID: 2b95f2c5a2cf
Revises: 
Create Date: 2025-10-29 16:09:14.727681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b95f2c5a2cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'current_vehicle_positions', 'trips', ['trip_id'], ['trip_id'])
    op.create_foreign_key(None, 'current_vehicle_positions', 'routes', ['route_id'], ['id'])
    op.drop_column('current_vehicle_positions', 'stop_id')
    op.drop_column('current_vehicle_positions', 'current_status')
    op.drop_column('routes', 'long_name')
    op.drop_column('routes', 'short_name')
    op.drop_column('vehicle_positions', 'stop_id')
    op.drop_column('vehicle_positions', 'current_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_positions', sa.Column('current_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicle_positions', sa.Column('stop_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('short_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('long_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('current_vehicle_positions', sa.Column('current_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('current_vehicle_positions', sa.Column('stop_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'current_vehicle_positions', type_='foreignkey')
    op.drop_constraint(None, 'current_vehicle_positions', type_='foreignkey')
    # ### end Alembic commands ###
